name: intola
description: An E-commerce mobile app for shopping, delivering and donating to people in need.

publish_to: "none"

version: 1.0.0+12

environment:
  sdk: 3.0.2

dependencies:
  flutter:
    sdk: flutter

  #user interface
  carousel_slider: ^4.0.0
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3

  #networking
  http: ^1.0.0

  #caching
  flutter_secure_storage: ^5.0.2
  cached_network_image: ^3.2.0

  #payments
  flutterwave_standard: ^1.0.8

  #utility
  image_picker: ^0.8.5

  #environment variables
  envied: ^0.3.0

  flutter_riverpod: ^2.0.0-dev.9
  mocktail: ^0.3.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  freezed: ^2.0.0
  envied_generator: ^0.3.0
flutter:
  uses-material-design: true

  assets:
    - assets/onboardingSvg/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
