name: intola
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #user interface
  carousel_slider: ^4.0.0
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2

  #networking
  http: ^0.13.4

  #caching
  flutter_secure_storage: ^5.0.2
  cached_network_image: ^3.2.0

  #payments
  flutterwave_standard: ^1.0.3

  #utility
  image_picker: ^0.8.5

  #environment variables
  flutter_dotenv: ^5.0.2

  
  flutter_riverpod: ^2.0.0-dev.9
  mocktail: ^0.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/onboardingSvg/
    - assets/images/
    - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
