  name: intola-unit-tests
  on: [push, workflow_dispatch]
  defaults:
    run:
      working-directory: ./client
  jobs:
    drive:
      runs-on : ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run : bash intola.sh
      - run : flutter test